### ISSUE TITLE
allergies_load.cql error

### ISSUE THREAD

**Issue by exaptations** [PacktPublishing/Cypher-Querying#2]
Mapping the source data to graph book pdf pg 89

git file allergies_load.cql 

line 13, column 33 (offset: 459))
"      WHERE row.STOP IS NOT NULL. and row.STOP <> ''"
                                 
Offending token NULL. 

Should be / Fix NULL without the '.'

**Comment by ravi-anthapu** [comment]
Thanks for pointing out the issue. I have fixed it now.
